### ISSUE TITLE
flyway没有生成表

### ISSUE THREAD

**Issue by jditlee** [hope-for/hope-boot#61]
运行项目flyway没有在数据库生成表

**Comment by NorthWard** [comment]
> 运行项目flyway没有在数据库生成表

应该是idea的问题
我的解决方案
在maven projects窗口点"Add Maven Projects"导入hope-flyway模块, 再clean , install一下就可以

**Comment by java-aodeng** [comment]
https://github.com/hope-for/hope-boot/wiki/5.%E4%BD%BF%E7%94%A8hope-boot%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E4%B8%8E%E5%85%A8%E5%AE%87%E5%AE%99%E6%9C%80%E5%B8%85%E7%9A%84%E4%BA%BA%E7%9A%84%E8%A7%A3%E7%AD%94  这个问题我有说过
