### ISSUE TITLE
目录和菜单新增了一个，并且分配了权限，用管理员登录，菜单没展示？

### ISSUE THREAD

**Issue by Cchenxx** [hope-for/hope-boot#64]
![Snipaste_2019-08-28_11-54-46](https://user-images.githubusercontent.com/43953970/63824743-c76d2700-c98a-11e9-9eab-f4279b536a14.png)
![Snipaste_2019-08-28_11-55-12](https://user-images.githubusercontent.com/43953970/63824748-cdfb9e80-c98a-11e9-8716-114777105d8e.png)

菜单是写死的吗？

**Comment by java-aodeng** [comment]
首页自己加，前端太渣，见谅
