### ISSUE TITLE
意见和建议啊

### ISSUE THREAD

**Issue by wangzhenjjcn** [hope-for/hope-boot#65]
给企业用的东西，你这登录页样式我看介绍图都搞得这么花里胡哨的
你说程序员还下载再看啊，
有些东西，原则很重要，态度也很重要的
个人觉得企业的软件也好，支持也好
稳定和可靠是要放第一的
不要太轻浮。稳重shi 有道理的。
不像个人的软件，坏了自己修一下就好
企业的软件down一下可能是十个人也可能是四五十个人在等着运转的。
所以不是设计风格上的问题，是再做代码和做软件的态度和初心上的问题
要更成熟稳重，多点责任感。

**Comment by java-aodeng** [comment]
嗯，收到反馈
