### ISSUE TITLE
SSO模块redis连接

### ISSUE THREAD

**Issue by aolei94521** [hope-for/hope-boot#69]
![JedisShardInfo](https://user-images.githubusercontent.com/20179373/64482617-ec358a00-d227-11e9-891a-4fa7e5239a30.png)
```
如果远程redis有auth，无法连接
```

**Comment by java-aodeng** [comment]
配置你的密码

**Comment by aolei94521** [comment]
这个工具类是你写的吗?redis拼写错误
很容易引起开发出问题
