### ISSUE TITLE
搞半天都没跑起来，烦躁

### ISSUE THREAD

**Issue by linyongfu2013** [hope-for/hope-boot#75]
12:04:54.605 logback [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xmlModelPlugin': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [springfox.documentation.schema.XmlModelPlugin] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15]

**Comment by liantengda** [comment]
不至于吧，下载下来就能用

**Comment by java-aodeng** [comment]
不至于吧，下载下来就能用
